version: "3.7"

services:
  nginx:
    image: nginx:alpine
    ports:
      - "28080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  account-book:
    image: jason/account-book
    build:
      context: account-book
    ports:
      - "28081:80"
    environment:
      - SERVER_PORT=80
      - CORS_ORIGINS_0=http://localhost:28080
      - OAUTH2_AUTHORIZED_REDIRECT_URIS=http://localhost:28080
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=http://localhost:28080/api/login/oauth2/code/google
    depends_on:
      - nginx
  account-book-react:
    image: json/account-book-react
    build:
      context: account-book-react
    ports:
      - "28082:80"
    depends_on:
      - nginx
      - account-book
