spring:
  application:
    name: "Account Book Server"
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    #url: jdbc:postgresql://localhost:15432/ac
    #username: postgres
    #password: postgres
    #driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: update
  security:
    user:
      name: "admin"
      password: "admin"
      roles: "ADMIN"
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}

server:
  port: ${SERVER_PORT:18080}
  servlet:
    context-path: "/api"

cors:
  origins:
    - "http://localhost:3000"

oauth2:
  authorizedRedirectUris:
    - "http://localhost:3000"
